### ISSUE TITLE
Initialization from Bart-Large does not work

### ISSUE THREAD

**Issue by YaserAlOsh** [AlaFalaki/compressedBART#1]
Hello,
Thank you for sharing the code for this project here.

I was trying to convert a Bart-large pre-trained checkpoint into CompressedBart. The checkpoint is available on HuggingFace. I used the following code:
 ```bart_checkpoint = 'philschmid/bart-large-cnn-samsum'
ae = architectures.Autoencoder(bart_encoder_emb_size=768,
                             first_proj=first_projection,
                             second_proj=second_projection,
                             third_proj=third_projection,
                             max_len=max_input_length)
# Initialize compressedBART
cbart_config = BartConfig.from_pretrained(bart_checkpoint)
cbart_config.enc_d_model = cbart_config.d_model
cbart_config.d_model = 384
CBart_model = architectures.CBartForConditionalGeneration.from_pretrained(checkpoint_dir,
                                                            config=cbart_config,ae=ae,ignore_mismatched_sizes=True)

# Load the weights and put it on GPU
ae_checkpoint = os.path.join( checkpoint_dir, "ae-checkpoint.pth" )
if torch.cuda.is_available():
    ae_checkpoint = torch.load(ae_checkpoint)

else:
    ae_checkpoint = torch.load(ae_checkpoint, map_location=torch.device('cpu'))

CBart_model.model.encoder.ae.load_state_dict(ae_checkpoint['model'])
del ae_checkpoint

#CBart_model.eval()

if torch.cuda.is_available():
    CBart_model.to("cuda")
```

So far everything works. However, after I pass the model to the Trainer class and start evaluating (or training) I get the following error:

RuntimeError: mat1 and mat2 shapes cannot be multiplied (4096x1024 and 768x576)

Is it because I am using the 384 checkpoint and should instead use the 540? Could you please share this checkpoint again since the link expired.

Many thanks.
Best wishes.

**Comment by AlaFalaki** [comment]
Hey @YaserAlOsh,

Thanks for raising the issue. I updated the checkpoint links. Please give them a try and let me know if they work.

As for the other question,
Unfortunately, the sample codes and checkpoints only work with the BART-base model. As you can see [here](https://github.com/AlaFalaki/compressedBART/blob/main/main.py#L36), the `bart_encoder_emb_size` is set to 768, which is the BART-base latent space. If you want to use this approach, you need to change the dimensions to be compatible.

**Comment by YaserAlOsh** [comment]
Hi @AlaFalaki 
Thank you for the prompt reply.
I did check but I do not see a link now.

Regarding BART-large models, what should the 'bart_encoder_emb_size' variable be? I suppose it is 1024 but that did not work too.

Edit:
I think the checkpoints as you said are only for BART-base, so it would not work even if 'bart_encoder_emb_size' is changed.
I would like to contribute and prepare checkpoints for bart-large on CNN/DailyMail. What would be the procedure to create them?
Thank you.

**Comment by AlaFalaki** [comment]
Oh, don't know how I removed it! I update the Readme file, and it should be good now.

In terms of training the model for BART-Large, there are two stages. You first need to train the Autoencoder on top of the BART-Large's output to learn the compression. Then you can put everything together and train the model for summarization. Unfortunately, I couldn't find the codes for training the models. I will let you know if I can find some pointers.

**Comment by YaserAlOsh** [comment]
It works now, thanks. 
I appreciate the additional information, it would be great to get some clues, thank you!
